navigation:
  header:
    - href: "about.html"
      text: "About"
    - href: "now.html"
      text: "Now"
    - href: "blog.html"
      text: "Blog"
    - href: "tags.html"
      text: "Tags"
  footer:
    - href: "about.html"
      text: "About"
    - href: "now.html"
      text: "Now"
    - href: "blog.html"
      text: "Blog"
    - href: "tags.html"
      text: "Tags"
    - href: "archive.html"
      text: "Archive"
