skills:
  # Core languages
  - name: "Go"
    icon: "go.svg"
  - name: "Python"
    icon: "python.svg"
  - name: "TypeScript"
    icon: "typescript.svg"
  - name: "Ruby"
    icon: "ruby.svg"

  # Platform & DevOps & Cloud
  - name: "Grafana"
    icon: "grafana.svg"
  - name: "Docker"
    icon: "docker.svg"
  - name: "Linux"
    icon: "linux.svg"
  - name: "GitHub Actions"
    icon: "githubactions.svg"
  - name: "Azure"
    icon: "azure.svg"

  # Backend & Frameworks
  - name: "Flask"
    icon: "flask.svg"
  - name: "Node.js"
    icon: "nodedotjs.svg"
  - name: "GraphQL"
    icon: "graphql.svg"

  # Databases
  - name: "PostgreSQL"
    icon: "postgresql.svg"
  - name: "MongoDB"
    icon: "mongodb.svg"

  # Frontend & Frameworks
  - name: "React"
    icon: "react.svg"
  - name: "Tailwind CSS"
    icon: "tailwindcss.svg"

specialties:
  - "Goroutines & Concurrency"
  - "Python Asyncio"
  - "REST APIs"
  - "Systemd Services"
  - "GitOps"
  - "OpenBao (Vault)"
  - "Loki Logging"
  - "Postgres JSONB"
  - "ADRs (Architecture Decision Records)"
  - "Test Driven Development (TDD)"
  - "CI/CD Pipelines"
  - "Architecture Integrity"