socials:
  - name: "GitHub"
    href: "https://github.com/victoriacheng15"
    icon: "github.svg"
  - name: "LinkedIn"
    href: "https://www.linkedin.com/in/victoriacheng15"
    icon: "linkedin.svg"
  - name: "YouTube"
    href: "https://www.youtube.com/@victoriacheng15"
    icon: "youtube.svg"
  - name: "Buy Me a Coffee"
    href: "https://www.buymeacoffee.com/victoriacheng15"
    icon: "buymeacoffee.svg"
  - name: "rss"
    href: "/rss.xml"
    icon: "rss.svg"
